version: "3"
services:
  web:
    build:
      context: .
    image: springboot
    networks:
      - spring
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - spring
    ports:
      - 33060:3306
networks:
  spring:
    driver: bridge